server:  
  port: ${PORT:3333}

spring:  
  application:
    name: customer-service
  data:
    mongodb:
      host: 192.168.99.100
      port: 27017
      username: micro 
      password: micro
      
eureka:  
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
      
ribbon:
  eureka:
    enabled: true