server:  
  port: ${PORT:5555}

spring:  
  application:
    name: transfer-service
 # data:
  ##   host: 192.168.99.100
    #  port: 27017
     # username: micro
      #password: micro

  spring:
    application:
      name: TRANSFER-SERVICE
    zipkin:
      base-url: http://127.0.0.1:9411/
#eureka:
 # client:
  #  serviceUrl:
   #   defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
 # instance:
  #  leaseRenewalIntervalInSeconds: 1
   ##
#ribbon:
 # eureka:
  #  enabled: true